apiVersion: v1
name: authelia
version: 0.1
appVersion: 3.16.2
description: A full-featured authentication server
home: https://www.authelia.com
icon: https://raw.githubusercontent.com/clems4ever/authelia/master/images/authelia.logo.png
keywords:
- security
- totp
- authentication
maintainers:
- email: at.mccann@gmail.com
  name: MadD0c
sources:
- https://github.com/clems4ever/authelia
version: 0.1.2
