apiVersion: v1
kind: Secret
metadata:
  name: {{ template "phpldapadmin.fullname" . }}-secret
  labels:
    app: {{ template "phpldapadmin.name" . }}
    chart: {{ template "phpldapadmin.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.extraLabels }}
{{ toYaml .Values.extraLabels | indent 4 }}
{{- end }}
type: Opaque
data:
  jwt_secret: {{ toYaml .Values.secrets.jwt_secret | b64enc | quote }}     
  duo_secret: {{ toYaml .Values.secrets.duo_secret_key | b64enc | quote }}
  session_secret: {{ toYaml .Values.secrets.session_secret | b64enc | quote }} 
  redis_password: {{ toYaml .Values.secrets.redis_password | b64enc | quote }} 
  sql_password: {{ toYaml .Values.secrets.DBPassword | b64enc | quote }}
  ldap_password: {{ toYaml .Values.secrets.ldap_password | b64enc | quote }}
  smtp_password: {{ toYaml .Values.secrets.smtp_password | b64enc | quote }}
