apiVersion: v1
kind: Secret
metadata:
  name: {{ template "phpldapadmin.fullname" . }}-secret
  labels:
    app: {{ template "phpldapadmin.name" . }}
    chart: {{ template "phpldapadmin.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.extraLabels }}
{{ toYaml .Values.extraLabels | indent 4 }}
{{- end }}
type: Opaque
data:
  ldap_password: {{ toYaml .Values.ldap.password | b64enc | quote }}
