apiVersion: v1
kind: Secret
metadata:
  name: {{ template "authelia.fullname" . }}-secret
  labels:
    app.kubernetes.io/name: {{ include "authelia.name" . }}
    helm.sh/chart: {{ include "authelia.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  jwt_secret: {{ toYaml .Values.secrets.jwt_secret | b64enc | quote }}     
  duo_secret: {{ toYaml .Values.duo.secret_key | b64enc | quote }}
  session_secret: {{ toYaml .Values.secrets.session_secret | b64enc | quote }} 
  redis_password: {{ toYaml .Values.redis.redispassword | b64enc | quote }} 
  sql_password: {{ toYaml .Values.externaldb.DBPassword | b64enc | quote }}
  ldap_password: {{ toYaml .Values.ldap.password | b64enc | quote }}
  smtp_password: {{ toYaml .Values.smtp.password | b64enc | quote }}
 