apiVersion: v1
kind: Secret
metadata:
  name: {{ template "authelia.fullname" . }}-secret
  labels:
    app.kubernetes.io/name: {{ include "authelia.name" . }}
    helm.sh/chart: {{ include "authelia.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  users_database.yml: {{ toYaml .Values.authelia.fileAuth | b64enc | quote }}
            - key: jwt_secret
              path: jwt
            - key: duo_secret
              path: duo
            - key: session_secret
              path: session
            - key: redis_password
              path: redis_password
            - key: sql_password
              path: sql_password
            - key: ldap_password
              path: ldap_password
            - key: smtp_password
              path: smtp_password