apiVersion: v1
kind: Service
metadata:
  name: {{ include "authelia.fullname" . }}
  labels:
{{ include "authelia.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 9091
      protocol: TCP
      name: auth-port
  selector:
    app.kubernetes.io/name: {{ include "authelia.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
