apiVersion: v1
kind: Secret
metadata:
  name: {{ template "phpmyadmin.fullname" . }}-secret
  labels:
    app: {{ template "phpmyadmin.name" . }}
    chart: {{ template "phpmyadmin.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.extraLabels }}
{{ toYaml .Values.extraLabels | indent 4 }}
{{- end }}
type: Opaque
data:
  PHPLDAPADMIN_LDAP_HOSTS: {{ toYaml .Values.ldap_hosts | b64enc | quote }}
